GET http://localhost:3000/protected
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJVc2VyIiwiaWF0IjoxNzEzOTYxOTI4fQ.HKXLkqZD1bFG2NxUf4YHaiizcIP8KwPWGgOYF7b4u9o

###

GET http://localhost:3000/protected
x-auth-token: invalid_token

###

GET http://localhost:3000/protected

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "User",
  "password": "password"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "User",
  "password": "wrong_password"
}

